### ISSUE TITLE
-d and -m not working

### ISSUE THREAD

**Issue by pschrammel** [steelheaddigital/delayed_job_celluloid#2]
Hi,
how can I put the process into background and monitor it? 
THX

**Comment by pschrammel** [comment]
Okay my fault. I just installed the gem (which is out of date). Would be nice if you would release a new version of it. THX

**Comment by steelheaddigital** [comment]
Thanks for letting me know about this.  I'll update the gem. That said, I haven't used this in quite a while and I'm not sure how well it's going to work with Ruby 2.x since the memory profile has changed so much. Another user reported problems with deadlocks on Ruby 2.x so be careful. I've moved to using Sidekiq for background processing as multithreading is well supported and it can do everything DJ can do.  It also has the benefit of using Redis for it's data store which is a much faster and better solution than using the database like DJ does. If you really want a robust multithreaded background job processor I would suggest you take a look at Sidekiq instead of using DJ.

**Comment by pschrammel** [comment]
THX, I'll have a look.
